import express from "express";
import swaggerUi from "swagger-ui-express";
let swaggerDocument: any = {};
try {
  // swagger.json is generated by `tsoa swagger`
  swaggerDocument = require('../dist/swagger.json');
} catch (e) {
  // If the file does not exist (e.g., first run), keep empty object
  console.warn('Swagger JSON not found, docs route disabled');
}

export const swaggerRouter = express.Router();
if (process.env.NODE_ENV !== "production") {
  swaggerRouter.use("/docs", swaggerUi.serve, swaggerUi.setup(swaggerDocument));
}
